@startuml standart bank deposit process
!include assets/C4_templates/C4_Container.puml

title Целевая архитектура банка Стандарт (депозитный процесс)

Person_Ext(user, "Клиент", "")

Container(internet_bank, "Интернет-банк", "", "")
Container(site, "Интернет-банк", "", "")
Container(abs, "АБС", "", "")
Container(call_center, "Система колл-центра", "", "")
Container(call_center_partner, "Система партнёрского колл-центра", "", "")
Container(deposit_service, "Сервис депозитов", "", "")



ContainerQueue(eventq, "Брокер событий", "Kafka")
ContainerDb(abs_db, "БД АБС", "")


' === СВЯЗИ ===

' Rel(user, gui, "HTTPS", "Веб-интерфейс")
' Rel(gui, bff, "HTTPS", "API запросы")
' Rel(bff, gateway, "HTTP", "Маршрутизация")
' Rel(gateway, user_srv, "HTTP", "Управление пользователями")
' Rel(gateway, streaming_srv, "HTTP", "Стриминг контента")
' Rel(gateway, metadata_srv, "HTTP", "Метаданные фильмов")
' Rel(gateway, billing_srv, "HTTP", "Платежи и подписки")
' Rel(gateway, marketing_srv, "HTTP", "Маркетинговые кампании")
' Rel(gateway, ugc_srv, "HTTP", "Пользовательский контент")

' Rel(user_srv, eventq, "Publish", "События пользователей")
' Rel(streaming_srv, eventq, "Publish", "События просмотров")
' Rel(billing_srv, eventq, "Publish", "События платежей")
' BiRel(eventq, event_srv, "Subscribe/Publish", "Обработка событий")

' Rel(ugc_srv, clickhouse, "SQL", "Аналитика UGC")
' Rel(event_srv, clickhouse, "SQL", "Аналитика событий")

' Rel(streaming_srv, S3, "S3 API", "Видеофайлы")
' Rel(streaming_srv, content_srv, "HTTP", "Получение контента")

' Rel(content_srv, external_source, "HTTP", "Внешние API")

@enduml
